apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-go-app
  name: gitops-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-go-app
  template:
    metadata:
      labels:
        app: gitops-go-app
    spec:
      containers:
      - image: docker.pkg.github.com/makocchi-git/gitops-go-app:2
        name: gitops-go-app
      imagePullSecrets:
      - name: dockerconfigjson-github-com
